config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root to: 'pages#home', as: :authenticated_root
    end

    unauthenticated :user do
      root to: "devise/sessions#new", as: :unauthenticated_root
    end
  end

  resources :foods
  resources :public_recipes, only: [:index]

  resources :recipes do 
    resources :recipe_foods, only: [:create, :destroy, :index, :new]
  end

  get 'shopping_list', to: 'recipes#shopping_list', as: 'shopping_list'

  root "pages#home"

  resources :inventories do
    resources :inventory_foods, except: :show
  end
end

app/models/inventory_food.rb
class InventoryFood < ApplicationRecord
  belongs_to :inventory
  belongs_to :food

  validates :quantity, comparison: { greater_than: 0 }
end

app/controllers/inventory_foods_controller.rb
class InventoryFoodsController < ApplicationController
  def new
    @inventory = Inventory.find(params[:inventory_id])
    @inventory_food = InventoryFood.new
    @foods = Food.order(:name)
    render :new
  end

  def create
    @inventory = Inventory.find(params[:inventory_id])
    @inventory_food = @inventory.inventory_foods.build(inventory_food_params)
    if @inventory_food.food_id.blank?
      flash[:alert] = 'Please select a food.'
      render :new
      return
    end
    if @inventory_food.save
      flash[:notice] = 'Inventory Food added successfully!'
      redirect_to inventory_path(@inventory)
    else
      @foods = Food.order(:name)
      render :new
    end
  end

  def destroy
    @inventory_food = InventoryFood.find(params[:id])
    inventory = @inventory_food.inventory
    @inventory_food.destroy
    flash[:notice] = 'Inventory food was successfully removed'
    redirect_to "/inventories/#{inventory.id}"
  end

  private

  def inventory_food_params
    params.require(:inventory_food).permit(:inventory_id, :food_id, :quantity)
  end
end

app/views/inventory_foods/new.html.erb
<div class="flex justify-center mt-48 mb-48 container mx-auto">
  <div class="w-3/5 bg-white shadow-lg p-10">
    <%= form_with model: @inventory_food, url: inventory_inventory_foods_path(@inventory) do |f| %>
      <div class="mb-4 flex justify-between items-center">
        <div class="mr-4">
          <%= f.label :food_id, "Food:" %>
          <%= f.collection_select :food_id, @foods, :id, :name, { prompt: "Select a food" }, class: "form-control custom-select", required: true %>
        </div>
        <div>
          <%= f.label :quantity %>
          <%= f.number_field :quantity, autofocus: true, autocomplete: "quantity", class: "form-control custom-border", required: true %>
        </div>
      </div>
      <div class="flex justify-center">
        <%= f.submit "Add Food", class: "btn btn-outline-dark btn-sm bg-blue-500 hover:bg-blue-700 text-white mt-5 py-2 px-6" %>
      </div>
    <% end %>
  </div>
</div>