config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root to: 'pages#home', as: :authenticated_root
    end

    unauthenticated :user do
      root to: "devise/sessions#new", as: :unauthenticated_root
    end
  end

  resources :foods
  resources :public_recipes, only: [:index]

  resources :recipes do 
    resources :recipe_foods, only: [:create, :destroy, :index, :new]
  end

  get 'shopping_list', to: 'recipes#shopping_list', as: 'shopping_list'

  root "pages#home"

  resources :inventories do
    resources :inventory_foods, except: :show
  end
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
  has_many :inventory_foods
  has_many :foods, through: :inventory_foods

  validates :description, presence: true
  validates :name, presence: true, length: { minimum: 3, maximum: 100 }
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  def index
    @inventories = Inventory.all
  end

  def show
    @inventory = Inventory.includes(inventory_foods: :food).find(params[:id])
    @inventory_id = @inventory.id
    @inventory_food = @inventory.inventory_foods
  end

  def destroy
    @inventory = Inventory.find(params[:id])

    # Delete the associated inventory_foods first
    @inventory.inventory_foods.destroy_all

    if @inventory.destroy
      flash[:notice] = 'Inventory deleted successfully!'
    else
      # Handle the case when the inventory cannot be deleted
      flash[:error] = 'Error deleting inventory!'
    end
    redirect_to inventories_path
  end

  def new
    @new_inventory = Inventory.new
  end

  def create
    inventory = Inventory.new(user: current_user, name: params[:inventory][:name],
                              description: params[:inventory][:description])
    respond_to do |format|
      if inventory.save
        flash[:notice] = 'Created an inventory successfully'
        format.html { redirect_to '/inventories' }
      else
        flash[:error] = "Failed to create an inventory: #{inventory.errors.full_messages.join(', ')}"
        format.html { redirect_to '/inventories/new' }
      end
    end
  end
end

app/views/inventories/index.html.erb
<div class="container mx-auto max-w-md">
  <div class="mb-6 flex justify-end">
    <% if current_user %>
      <%= link_to "Add inventory", new_inventory_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-4" %>
    <% end %>
  </div>
  <% if @inventories.present? %>
    <% @inventories.each do |inventory| %>
      <div class="border border-gray-400 p-4 mb-4 flex flex-col md:flex-row">
        <div class="flex-shrink-0 md:mb-0 md:mr-4 w-24">
          <p class="text-lg font-bold text-sky-700"><%= inventory.name %></p>
          <!-- Move the "DELETE" button below the inventory name -->
          <div class="mt-4">
            <% if current_user %>
              <%= button_to "DELETE", inventory_path(inventory), method: :delete, class: "bg-red-500 hover:bg-red-600 text-white px-2 py-1 rounded", form: { data: { turbo_confirm: "Are you sure you want to delete this inventory?" }} %>
            <% else %>
              <p>N/A</p>
            <% end %>
          </div>
        </div>
        <div class="flex-grow">
          <p class="text-sm"><%= inventory.description %></p> <!-- Display the description for each inventory -->
        </div>
      </div>
    <% end %>
  <% else %>
    <h3 class="text-2xl font-semibold mb-4 text-center">Add New Inventory Currently You Do Not Have Any Inventory In The List</h3>
  <% end %>
</div>

app/views/inventories/new.html.erb
<div class="flex justify-center mt-24 mb-48 container mx-auto">
  <div class="w-3/5 bg-white shadow-lg p-10">
    <h1 class="text-2xl font-bold border-b-2">Add new inventory</h1>
    <%= form_with model: @new_inventory, url: '/inventories' do |form| %>
      <br>
      <%= form.label :name, class: 'font-semibold pb-1 mt-4' %><br />
      <%= form.text_field :name, placeholder: 'Name of the inventory', class: 'py-2 px-4 border w-full focus:outline-blue-400', required: true %>
      <br>
      <%= form.label :description, class: 'font-semibold pb-1 mt-4' %><br />
     <%= form.text_area :description, placeholder: 'Description of the inventory', class: 'py-2 px-4 border w-full focus:outline-blue-400', required: true %>
      <br>
      <%= form.submit class: 'bg-blue-500 py-3 px-6 text-white cursor-pointer hover:bg-blue-700 mt-4' %>
    <% end %>
  </div>
</div>

app/views/inventories/show.html.erb
<div class="flex justify-center mt-48 mb-48 container mx-auto">
  <div class="w-3/5 bg-white shadow-lg p-10">
    <h1 class="text-2xl font-semibold text-center"><%= @inventory.name.capitalize %></h1>
    
    <div class="flex justify-end mt-3">
      <%= link_to 'Add food', new_inventory_inventory_food_path(inventory_id: @inventory_id) %>
    </div>
    
    <table class="min-w-full table-auto border bg-white mt-2">
      <% if @inventory_food.present? %>
        <thead class="bg-gray-400 text-white">
          <tr>
            <th class="py-3 text-left px-5 font-semibold">Food</th>
            <th class="py-3 text-left px-5 font-semibold">Quantity</th>
            <th class="py-3 text-left pr-5 font-semibold" colspan="3">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @inventory.inventory_foods.each do |inventory_food| %>
            <tr class="hover:bg-gray-200 border">
              <td class="right py-3 px-5"><%= inventory_food.food.name.capitalize %></td>
              <td class="right py-3 px-5"><%= "#{inventory_food.quantity} #{inventory_food.food.measurement_unit}" %></td>
              <td>
                  <%= button_to 'Remove', inventory_inventory_food_path(@inventory, inventory_food),
                      method: :delete, class: 'custom-button' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      <% end %>
    </table>
  </div>
</div>