config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root to: 'pages#home', as: :authenticated_root
    end

    unauthenticated :user do
      root to: "devise/sessions#new", as: :unauthenticated_root
    end
  end

  resources :foods
  resources :public_recipes, only: [:index]

  resources :recipes do 
    resources :recipe_foods, only: [:create, :destroy, :index, :new]
  end

  get 'shopping_list', to: 'recipes#shopping_list', as: 'shopping_list'

  root "pages#home"

  resources :inventories do
    resources :inventory_foods, except: :show
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :foods, through: :recipe_foods

  validates :name, presence: true
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true
  validates :description, presence: true
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_recipe, only: %i[destroy]

  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def show
    @recipe = Recipe.find(params[:id])
    @user = @recipe.user
    @recipe_foods = @recipe.recipe_foods
    @inventories = Inventory.all
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipes_path, notice: 'Recipe Created Successfully' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_path, notice: 'Recipe Destroyed Successfully' }
      format.json { head :no_content }
    end
  end

  def shopping_list
    @recipe_id = params[:recipe_id]
    @inventory_id = params[:inventory_id]
    @recipe = Recipe.includes(recipe_foods: :food).find(@recipe_id)
    @inventory = Inventory.find(@inventory_id)
    inventory_foods_id = @inventory.foods.pluck(:id)
    @missing_foods = @recipe.recipe_foods.reject { |food_recipe| inventory_foods_id.include?(food_recipe.food_id) }
  end

  def update
    @recipe = Recipe.find_by(id: params[:id])
    public = params[:public] == '1'
    if @recipe.update_attribute(:public, public)
      flash[:notice] = 'Recipe updated successfully.'
    else
      flash[:alert] = 'Failed to update recipe.'
    end
    redirect_to recipe_path(@recipe)
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public, :user)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_modal.html.erb
<div class="hidden fixed inset-0 bg-black bg-opacity-50 z-50" id="modal">
  <div class="w-3/5 bg-white shadow-lg p-8 mx-auto mt-20">
    <h2 class="text-3xl font-semibold mb-4 text-center">Shopping List</h2>
    <!-- Add the shopping list content here -->
    <p class="text-center text-gray-600">You can list the ingredients needed for this recipe here.</p>
    <div class="flex justify-center mt-4">
      <button class="py-3 px-6 bg-blue-500 text-white font-semibold rounded-lg hover:bg-blue-600 focus:outline-none focus:ring focus:border-blue-300" onclick="closeModal()">Close</button>
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<div class="container mx-auto max-w-md">
  <div class="mb-6 flex justify-end">
    <% if current_user %>
      <%= link_to "Add Recipe", new_recipe_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-4", id: "add-recipe-link" %>
    <% end %>
  </div>
  <% @recipes.each do |recipe| %>
    <div class="border border-gray-400 p-4 mb-4 flex flex-col md:flex-row">
      <div class="flex-shrink-0 md:mb-0 md:mr-4 w-24">
        <p class="text-lg font-bold text-sky-700"><%= recipe.name %></p>
        <!-- Move the "Remove" button below the recipe name -->
        <div class="mt-4">
          <%= button_to 'Remove', recipe_path(recipe),
                        method: :delete,
                        class: "bg-red-500 hover:bg-red-600 text-white px-2 py-1 rounded",
                        form: { data: { turbo_confirm: "Are you sure you want to delete this recipe?" }} %>
        </div>
      </div>
      <div class="flex-grow">
        <p class="text-sm"><%= recipe.description %></p>
        <div class="mt-4">
          <p><%= link_to 'Show', recipe_path(recipe), class: "text-sky-500 underline" %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/recipes/new.html.erb
<div class="container mx-auto max-w-sm">
  <div class="mb-6 bg-gradient-to-br from-sky-500 via-sky-600 to-sky-700 rounded-lg shadow-lg p-8 text-white">
    <h2 class="text-3xl font-semibold mb-6 text-center">Add New Recipe</h2>

    <%= form_with(model: @recipe) do |form| %>
      <% if @recipe.errors.any? %>
        <div class="bg-red-200 text-red-800 p-4 rounded mb-4">
          <h2 class="font-semibold mb-2"><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>
          <ul>
            <% @recipe.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="mb-4">
        <%= form.label :name, class: "block font-semibold mb-2 text-white" %>
        <%= form.text_field :name, class: "w-full px-4 py-2 bg-blue-200 bg-opacity-75 border border-gray-300 rounded-lg focus:outline-none focus:ring focus:border-blue-300 text-blue-900 placeholder-blue-500 placeholder-opacity-75" %>
      </div>

      <div class="flex justify-between mb-4">
        <div class="w-1/2 pr-2">
          <%= form.label :preparation_time, class: "block font-semibold mb-2 text-white" %>
          <%= form.text_field :preparation_time, class: "w-full px-4 py-2 bg-blue-200 bg-opacity-75 border border-gray-300 rounded-lg focus:outline-none focus:ring focus:border-blue-300 text-blue-900 placeholder-blue-500 placeholder-opacity-75" %>
        </div>
        <div class="w-1/2 pl-2">
          <%= form.label :cooking_time, class: "block font-semibold mb-2 text-white" %>
          <%= form.text_field :cooking_time, class: "w-full px-4 py-2 bg-blue-200 bg-opacity-75 border border-gray-300 rounded-lg focus:outline-none focus:ring focus:border-blue-300 text-blue-900 placeholder-blue-500 placeholder-opacity-75" %>
        </div>
      </div>

      <div class="mb-4">
        <%= form.label :description, class: "block font-semibold mb-2 text-white" %>
        <%= form.text_area :description, class: "w-full px-4 py-2 h-16 bg-blue-200 bg-opacity-75 border border-gray-300 rounded-lg focus:outline-none focus:ring focus:border-blue-300 text-blue-900 placeholder-blue-500 placeholder-opacity-75" %>
      </div>

      <div class="mb-4 flex items-center">
        <%= form.label :public, class: "block font-semibold mr-2 text-white" %>
        <%= form.check_box :public, class: "form-checkbox h-5 w-5 text-blue-500" %>
        <span class="text-white text-sm"></span>
      </div>

      <div class="text-center">
        <%= form.submit "Save Recipe", class: "w-full px-6 py-2 bg-sky-700 hover:bg-sky-800 focus:outline-none focus:ring focus:border-blue-300 rounded-lg transform transition-transform motion-reduce:transform-none" %>
      </div>
    <% end %>
  </div>
</div>

app/views/recipes/shopping_list.html.erb
<div class="container mx-auto max-w-md">
  <div class="mb-6 flex justify-end"> 
    <% if current_user %>
      <%= link_to "Add Food", new_food_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-4" %>
    <% end %>
  </div>
  <section>
    <div class="d-flex justify-content-between align-items-center mb-4">
      <div>
        <p class="font-bold">Amount of food to buy: <%= @missing_foods.count %></p>
        <p class="font-bold">Total value of food needed: $<%= @missing_foods.sum { |food| food.food.price } %></p>
      </div>
      <div>
        <p class="font-bold">Inventory: <%= link_to @recipe.name, recipe_path(@recipe) %></p>
        <p class="font-bold">Inventory: <%= link_to @inventory.name, inventory_path(@inventory) %></p>
      </div>
    </div>
    <div class="overflow-x-auto">
      <table class="w-full border-collapse border border-gray-400">
        <thead>
          <tr class="bg-gray-200">
            <th class="border border-gray-400 px-4 py-2">Food</th>
            <th class="border border-gray-400 px-4 py-2">Quantity</th>
            <th class="border border-gray-400 px-4 py-2">Price</th>
            <th class="border border-gray-400 px-4 py-2">Action</th>
          </tr>
        </thead>
        <tbody>
          <% @missing_foods.each do |food| %>
            <tr>
              <td class="border border-gray-400 px-4 py-2"><%= food.food.name %></td>
              <td class="border border-gray-400 px-4 py-2"><%= food.quantity %></td>
              <td class="border border-gray-400 px-4 py-2">$<%= food.food.price %></td>
              <td class="border border-gray-400 px-4 py-2">
                <% if current_user %>
                  <%= button_to "DELETE", recipe_recipe_food_path(@recipe, food), method: :delete, class: "bg-red-500 hover:bg-red-700 text-white font-bold py-1 px-2 rounded" %>
                <% else %>
                  <p>N/A</p>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </section>
</div>

app/views/recipes/show.html.erb
<div class="flex justify-center mt-48 mb-48 container mx-auto">
  <div class="w-3/5 bg-white shadow-lg p-10">

    <div>
      <h2 class="text-3xl text-gray-700 font-semibold text-center"><%= @recipe.name %></h2>
      <div>
        <% if current_user %>
          <div class="flex justify-end">
            <%= form_with url: recipe_path(@recipe.id), method: "put" do |form| %>
              <div>
                <%= form.label :public, for: "flexSwitchCheckChecked", class: "cursor-pointer text-xl"%>
                <%= form.check_box :public, id: "flexSwitchCheckChecked", onchange: "this.form.submit();", checked: @recipe.public %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="flex items-center justify-normal mb-2 mt-4">
  <span class="font-semibold text-gray-800">Preparation time:</span>
  <span class="text-lg font-semibold text-gray-700">&nbsp;&nbsp;<%= @recipe.preparation_time %></span>
</div>
<div class="flex items-center justify-normal mb-1">
  <span class="font-semibold text-gray-800">Cooking time:</span>
  <span class="text-lg font-semibold text-gray-700">&nbsp;&nbsp;<%= @recipe.cooking_time %></span>
</div>
<div class="flex items-center justify-normal mb-1">
  <h3 class="font-semibold text-gray-800">Cooking steps:</h3>
  <p class="text-gray-500">&nbsp;&nbsp;<%= @recipe.description %></p>
</div>

    </div>
    <% if current_user %>
      <div class="flex justify-between mt-4">
      <%= link_to "Generate shopping list", '#', class: "py-3 px-6 border-sky-500 mb-3 text-orange hover:text-white border hover:bg-sky-600", onclick: 'openModal(event)' %>
        <%= link_to "Add ingredient", new_recipe_recipe_food_path(@recipe.id), class: "py-3 px-6 bg-sky-500 mb-3 text-white hover:bg-sky-600" %>
      </div> 
    <% else %>
      <div class="flex justify-between mt-4">
        <%= button_to "Generate shopping list", '#', class: "py-3 px-6 border-orange-500 mb-3 text-orange hover:text-white border hover:bg-orange-700 opacity-50 cursor-not-allowed", disabled: true %>
        <%= button_to "Add ingredient", '#', class: "py-3 px-6 bg-orange-500 mb-3 text-white hover:bg-orange-700 opacity-50 cursor-not-allowe", disabled: true %>
      </div>
    <% end %>
    <table  class="min-w-full table-auto border bg-white mt-5">
      <thead class="bg-sky-400 text-white">
        <tr>
          <th class="py-3 text-left px-5 font-semibold">Food</th>
          <th class="py-3 text-left px-5 font-semibold">Quantity</th>
          <th class="py-3 text-left px-5 font-semibold">Price</th>
          <% if current_user %>
            <th class="py-3 text-left pr-5 font-semibold" colspan="3">Action</th>
          <% end %>
        </tr>
      </thead>
        <tbody>
          <% @recipe_foods.each do |recipe_food| %>
            <tr class="hover:bg-gray-200 border">
              <td class="right py-3 px-5"><%= recipe_food.food.name %></td>
              <td class="right py-3 px-5"><%= "#{recipe_food.quantity} #{recipe_food.food.measurement_unit}" %></td>
              <td class="right py-3 px-5"><%= "$#{recipe_food.quantity * recipe_food.food.price}" %></td>
              <% if current_user %>
                <td><%= button_to 'Delete', recipe_recipe_food_path(@recipe.id, recipe_food.id), method: :delete, class: 'text-red-400', form: { data: { turbo_confirm: "Are you sure you want to delete this ingredient?" }} %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
    </table>
   </div>
</div>

<div id="myModal" class="modal">
  <div class="modal-content">
    <span class="close">&times;</span>
    <h2 class="text-center font-semibold text-3xl">Generating Shopping List</h2>
    <p class="my-3">Choose an inventory to use</p>
    <%= form_with(url: shopping_list_path, method: :get) do |f| %>
      <div class="flex items-center justify-between">
        <div class="w-2/5 pr-2"> 
          <div class="border py-2 px-4">
            <%= f.select :inventory_id, options_for_select(@inventories.map { |inventory| [inventory.name, inventory.id] }), { prompt: 'Select an Inventory' }, class: 'focus:outline-none w-full', required: true %>
          </div>
        </div>
        <div class="w-2/5"> 
          <%= f.hidden_field :recipe_id, value: @recipe.id, required: true, class: 'border py-2 px-4' %>
          <%= f.submit "Generate", class: 'py-3 px-8 bg-sky-500 text-white hover:bg-sky-700 cursor-pointer w-full'%>
        </div>
      </div>
    <% end %>
  </div>
</div>



<%= javascript_include_tag "modal", "data-turbo-track": "reload" %>