config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root to: 'pages#home', as: :authenticated_root
    end

    unauthenticated :user do
      root to: "devise/sessions#new", as: :unauthenticated_root
    end
  end

  resources :foods
  resources :public_recipes, only: [:index]

  resources :recipes do 
    resources :recipe_foods, only: [:create, :destroy, :index, :new]
  end

  get 'shopping_list', to: 'recipes#shopping_list', as: 'shopping_list'

  root "pages#home"

  resources :inventories do
    resources :inventory_foods, except: :show
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :inventories
  has_many :recipes

  def admin?
    role == 'admin'
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/user/_session_manager.html.erb
<% if current_user %>
      <ul class="flex space-x-4">
        <li>
          <%= link_to "Home", root_path, class: "font-medium text-blue-700" %>
        </li>
        <li>
          <%= link_to "Foods", foods_path, class: "font-medium text-blue-700" %>
        </li>
        <li>
          <%= link_to "Recipes", recipes_path, class: "font-medium text-blue-700" %>
        </li>
        <li>
          <%= link_to "Public Recipes", public_recipes_path, class: "font-medium text-blue-700" %>
        </li>
        <li>
          <%= link_to "Inventories", inventories_path, class: "font-medium text-blue-700" %>
        </li>
        <li>
        <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure you want to sign out?' }, class: 'w-full text-left pl-4' %>
        </li>
      </ul>
    <% else %>
      <%= link_to "Sign In", new_user_session_path, class: "block py-2 px-4 text-white rounded bg-blue-500 hover:bg-blue-600 font-semibold" %>
    <% end %>